# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

quitOnTopLevelReturn: true
disableStartupPopups: true

git:
  # branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never # BUG: Doesn't work on windows (https://github.com/jesseduffield/lazygit/issues/1453)
      # colorArg: never
      # pager: ydiff -p cat -s --wrap --width={{columnWidth}}
  # log:
  #   showWholeGraph: true

gui:
  # splitDiff: always
  sidePanelWidth: .2
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  timeFormat: 02 Jan 2006
  shortTimeFormat: 03:04
  showFileTree: false
  nerdFontsVersion: 3
  screenMode: normal # half | full
  filterMode: fuzzy

keybinding:
  universal:
    gotoTop: "g"
    gotoBottom: "G"
    nextPage: <c-d>
    prevPage: <c-u>
    nextTab: ">"
    prevTab: "<"
  files:
    toggleTreeView: "'"
  commits:
    viewResetOptions: U
