- yay:
    - hyprland
    - xdg-desktop-portal-hyprland
    - hyprpolkitagent-git
    - pipewire
    - wireplumber
    - hyprpaper
    - dunst # mako, swaync
    - rofi-wayland
    - waybar
    - python-pywal

- link:
    ~/.config/hypr:
      force: true
    ~/.config/waybar:
    ~/.config/rofi:
