- yay:
    - kvantum
    - dosfstools
    - ark
    - dolphin
    - partitionmanager
    - kdeconnect
    - sddm
    - plasma-framework5
- link:
    ~/.config/:
      glob: true
      path: kde/*
      force: true
