"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false

format = """\
$all $fill $python$shell
$jobs\
$battery\
$time\
$status\
$os\
$container\
$character"""

# right_format = "$cmd_duration$memory_usage$sudo$battery$os"

[fill]
  symbol = "â”€"

[line_break]
  disabled = true

[shell]
  disabled             = false
  format               = "$indicator"
  bash_indicator       = "[î¯Š ](bright-yellow)"
  fish_indicator       = "[ó°ˆº ](blue)"
  zsh_indicator        = "[ó°µ ](bright-purple)"
  powershell_indicator = "[î¯‡ ](cyan)"
  pwsh_indicator       = "[ó°¨Š ](blue)"
  cmd_indicator        = "[î¯„ ](yellow)"
  nu_indicator         = "[> ](#39884d)"
  xonsh_indicator      = "[@ ](purple)"
  unknown_indicator    = "[ï„¨ ](red)"

[username]
  # show_always = true
  format     = '[$user]($style)'
  style_user = 'yellow'

[hostname]
  # ssh_only = false
  format     = "[@($ssh_symbol )$hostname]($style)"
  ssh_symbol = 'ğŸŒ'
  # detect_env_vars = ['SSH_TTY', 'SSH_CONNECTION', 'SSH_CLIENT']

[localip]
  disabled = false
  # ssh_only = false

[directory]
  truncation_length = 7
  # truncate_to_repo = false
  # style = "bg:bright-black fg:cyan inverted"
  repo_root_style = "bold"
  read_only = " ï€£"
  read_only_style = "red"
  style = "cyan"
  format = """\
[$read_only]($read_only_style)\
[ $path]($style)\
"""
  repo_root_format = """\
[$read_only]($read_only_style)\
[ $before_root_path]($before_repo_root_style)\
[ï‚› $repo_root]($style $repo_root_style)\
[$path]($style)\
"""
  use_logical_path = false
  # fish_style_pwd_dir_length = 1

[git_branch]
  symbol = "ó°˜¬ "
  format = """[ $symbol$branch(:$remote_branch)]($style)"""
  style  = "purple"

[git_commit]
  format = '[\($hash$tag\)]($style)'
  style  = "#646A76"

[git_status]
  format           = "[($all_status$ahead_behind )]($style)"
  style            = "default"
  windows_starship = "/mnt/c/Users/McNamaraK/scoop/shims/starship.exe"
  conflicted       = "[ â€¼$count](red)"                                 # =
  stashed          = "[ î­‹ $count](white)"                              # \\$
  deleted          = "[ ó°†´$count](bold red)"                            # âœ˜
  renamed          = "[ î«  $count](bold yellow)"                        # Â»
  modified         = "[ î« $count](yellow)"                             # !
  staged           = "[ î«œ $count](green)"                              # +
  untracked        = "[ î¬² $count](bold black)"                         # ?
  diverged         = " â‡•$ahead_count/$behind_count"
  ahead            = "[ â‡¡$count](blue)"
  behind           = "[ â‡£$count](bold blue)"

[package]
  disabled = true
  format   = "[$symbol$version]($style)"
  style    = "bold yellow"

[lua]
  disabled = true

[python]
  symbol = "î˜† "
  style  = "blue"
  format = '[(\($symbol$virtualenv\) )]($style)'

[os]
  # disabled = false

[os.symbols]
  Windows          = "ó°² "
  Ubuntu           = "ó°•ˆ "
  SUSE             = "ïŒ” "
  Raspbian         = "ó°¿ "
  Mint             = "ó°£­ "
  Macos            = "ó°€µ "
  Manjaro          = "ïŒ’ "
  Linux            = "ó°Œ½ "
  Gentoo           = "ó°£¨ "
  Fedora           = "ó°£› "
  Alpine           = "ïŒ€ "
  Amazon           = "ï‰° "
  Android          = "îœ "
  Arch             = "ó°£‡ "
  Artix            = "ó°£‡ "
  CentOS           = "ïŒ„ "
  Debian           = "ó°£š "
  Redhat           = "ó±„› "
  RedHatEnterprise = "ó±„› "

[cmd_duration]
  disabled           = true
  style              = "bold yellow"
  format             = "[( $duration ï‰“)]($style)"
  show_notifications = true

[character]
  # disabled = true
  success_symbol            = '[ â¯](green)'
  error_symbol              = '[ â¯](red)'
  vimcmd_symbol             = '[ â®](cyan)'
  vimcmd_replace_one_symbol = '[ âœ˜](purple)'
  vimcmd_replace_symbol     = '[ âœ˜](bold yellow)'
  vimcmd_visual_symbol      = '[ ï®](yellow)'
