- yay:
    - cosmic
  # - cosmic-session
  # - cosmic-files
  # - cosmic-store
  # - cosmic-terminal
  # - cosmic-text-editor
  # - cosmic-wallpapers

- link:
    ~/.config/cosmic:

- sudo:
    - shell:
        - systemctl enable cosmic-greeter
        # - systemctl start cosmic-greeter
