- yay:
    - cosmic
    # - cosmic-session
    # - cosmic-files
    # - cosmic-store
    # - cosmic-terminal
    # - cosmic-text-editor
    # - cosmic-wallpapers
    - wl-clipboard

- link:
    ~/.config/cosmic:

- sudo:
    - shell:
        - systemctl enable cosmic-greeter
        # - systemctl start cosmic-greeter
