- yay:
    - cosmic
    # - cosmic-session
    # - cosmic-files
    # - cosmic-store
    # - cosmic-terminal
    # - cosmic-text-editor
    # - cosmic-wallpapers
    # - cosmic-launcher-git
    - power-profiles-daemon
    - wl-clipboard

- included:
    - .meta/configs/pipewire.yaml
    - .meta/configs/wezterm.yaml

- link:
    ~/.config/cosmic:
    ~/.config/gtk-3.0: theme/gtk-3.0
    ~/.config/gtk-4.0: theme/gtk-4.0

- sudo:
    - shell:
        - systemctl enable cosmic-greeter
        # - systemctl start cosmic-greeter
