- yay:
    - cosmic
    # - cosmic-session
    # - cosmic-files
    # - cosmic-store
    # - cosmic-terminal
    # - cosmic-text-editor
    # - cosmic-wallpapers
    # - cosmic-launcher-git
    - power-profiles-daemon
    - wl-clipboard
    - wezterm

- link:
    ~/.config/cosmic:
    ~/.config/wezterm:
    ~/.config/gtk-3.0: themes/gtk-3.0
    ~/.config/gtk-4.0: themes/gtk-4.0

- sudo:
    - shell:
        - systemctl enable cosmic-greeter
        # - systemctl start cosmic-greeter
