- yay:
    - hyprland
    - xdg-desktop-portal-hyprland
    - hyprpolkitagent-git
    # - qt5-wayland
    # - qt6-wayland
    # - nwg-look
    - wl-clipboard
    - clipboard
    - pipewire
    - wireplumber
    - hyprpaper
    - hyprpicker
    - dunst # mako, swaync
    - rofi-wayland
    - waybar
    - wlogout
    - python-pywal

# TODO: Need to add bluetooth

- link:
    ~/.config/hypr:
      force: true
    ~/.config/waybar:
    ~/.config/rofi:

- included:
    - .meta/configs/sddm.yaml
