# BUG: Need to fix flickering issue
- shell:
    - yay -R wezterm # wezterm doesn't start in Hyprland

- yay:
    - hyprland
    - xdg-desktop-portal-hyprland
    - hyprpolkitagent-git
    # - qt5-wayland
    # - qt6-wayland
    # - nwg-look
    - wl-clipboard
    - clipboard
    - pipewire
    - wireplumber
    - hyprpaper # backend wallpaper setter
    - waypaper # gui frontent for hyprpaper
    - hyprpicker
    - dunst # mako, swaync
    - rofi-wayland
    - waybar
    - wlogout
    - python-pywal
    - wezterm-git # wezterm doesn't start in Hyprland

# TODO: Need to add bluetooth

- link:
    ~/.config/hypr:
      force: true
    ~/.config/waybar:
      force: true
    ~/.config/rofi:
      force: true
    ~/.config/dunst:
      force: true

- included:
    - .meta/configs/sddm.yaml
