- paru:
    - cmake
    - meson
    - cpio

- shell:
    - hyprpm add https://github.com/hyprwm/hyprland-plugins
    - hyprpm add https://github.com/outfoxxed/hy3
    - hyprpm update
    - hyprpm enable hyprexpo
    - hyprpm enable hy3
    - hyprpm reload
