# BUG: Need to fix flickering issue

# - sudo:
#     - shell:
#         - yay -R wezterm # wezterm doesn't start in Hyprland

- yay:
    - hyprland
    - xdg-desktop-portal-hyprland
    # - hyprpolkitagent-git
    - polkit-gnome
    - qt5-wayland
    - qt6-wayland
    - nwg-look # GTK Theme setter
    - hyprcursor # cursor backend
    - nordzy-hyprcursors # hyprcursor theme
    - nordzy-cursors # xcursor and gtk cursor theme
    - udiskie # automount usb drives
    - pipewire # audio server
    - wireplumber
    - hyprpaper # backend wallpaper setter
    - waypaper # gui frontent for hyprpaper
    - hyprpicker # color picker
    - dunst # mako, swaync
    - rofi-wayland # launcher (apps,windows,other)
    - cliphist # clipboard manager (uses wl-clipboard)
    - waybar # status bar
    - wlogout # logout menu
    - python-pywal
    # - wezterm-git # wezterm doesn't start in Hyprland

# TODO: Need to add bluetooth

- included:
    - .meta/configs/kitty.yaml

- defaults:
    - link:
        force: true

- link:
    ~/.config/hypr:
    ~/.config/waybar:
    ~/.config/rofi:
    ~/.config/dunst:
    ~/.config/Kvantum: kde/Kvantum
# - included:
#     - .meta/configs/sddm.yaml
