- yay:
    - hyprland
    - xdg-desktop-portal-hyprland
    # - hyprpolkitagent-git
    - polkit-gnome # authentication agent
    - qt5-wayland # QT5 library
    - qt6-wayland # QT6 library
    # - qt5ct # QT5 config tool
    - qt6ct # QT6 config tool
    - kvantum
    - nwg-look # GTK Theme setter
    - hyprcursor # cursor backend
    - nordzy-hyprcursors # hyprcursor theme
    - nordzy-cursors # xcursor and gtk cursor theme
    - nordic-theme # GTK Theme
    - udiskie # automount usb drives
    - hyprpaper # backend wallpaper setter
    - waypaper # gui frontent for hyprpaper
    - hyprpicker # color picker
    - hyprlock # lock screen
    - dunst # mako, swaync
    - rofi-wayland # launcher (apps,windows,other)
    - cliphist # clipboard manager (uses wl-clipboard)
    - waybar # status bar
    - wlogout # logout menu
    - python-pywal
    - nm-connection-editor # NetworkManager gui
    - network-manager-applet # sys tray icon and menu
    - blueberry-wayland # bluetooth gui

- included:
    - .meta/configs/sddm.yaml
    - .meta/configs/pipewire.yaml
    - .meta/configs/wezterm.yaml
    # - .meta/configs/kitty.yaml

- defaults:
    link:
      force: true

- link:
    ~/.config/hypr:
    ~/.config/waybar:
    ~/.local/bin/reload-waybar: bin/reload-waybar
    ~/.config/rofi:
    ~/.config/dunst:
    ~/.config/wlogout:
    ~/.gtkrc-2.0:
    ~/.config/gtk-3.0:
    ~/.config/gtk-4.0:
    ~/.config/xsettingsd:
    ~/.config/.Xresources:
    # ~/.config/Kvantum: kde/Kvantum
