- paru:
    - plasma-meta
    - kvantum
    - konsole
    - dosfstools
    - ark
    - dolphin
    - partitionmanager
    - kdeconnect
    - plasma-framework5
    - isoimagewriter

- link:
    ~/.config/Kvantum: theme/Kvantum
    ~/.config/:
      glob: true
      path: kde/*
      force: true

- included:
    - .meta/configs/sddm.yaml
