- paru:
    - neovim
    - nodejs
    - npm

# - scoop:
#     apps:
#       - neovim

- link:
    ~/.config/nvim:
      if: uname
      force: true
    ~/AppData/Local/nvim:
      if: cmd.exe --version
      force: true
