- yay:
    - nushell

# - scoop:
#     apps:
#       - nushell

- link:
    ~/.config/nushell:
      if: uname
      force: true
    # ~/AppData/Local/nushell:
    #   if: cmd.exe --version
    #   force: true
