- yay:
    - pipewire
    - wireplumber
    - pipewire-pulse
    - pipewire-alsa
    # - pipewire-jack

- shell:
    - systemctl --user enable pipewire.service wireplumber.service pipewire-pulse.service
