# - included:
#     - .meta/configs/bash.yaml
#     - .meta/configs/yay.yaml

- link:
    ~/.face.icon: profile-crop.jpg

# - sudo:
#     - shell:
#         - [timedatectl set-local-rtc 1, Use local time for hwclock]
