[pyprland]
  plugins = ["scratchpads", "toggle_special", "expose"]

  [pyprland.variables]
    term = "wezterm start --always-new-process"
    #     term = "kitty"
    #     term = "alacritty"

[scratchpads.dropterm]
  animation = "fromTop"
  command   = "[term] --class=dropterm"
  class     = "dropterm"
  position  = "17% 6%"
  size      = "65% 60%"
  offset    = "200%"

  # [scratchpads.music]
  #   animation = "fromBottom"
  #   command   = "kitty --class kitty-pulsemixer -e pulsemixer"
  #   class     = "kitty-pulsemixer"
  #   size      = "50% 20%"
  #   offset    = "200%"

[scratchpads.taskbar]
  animation = "fromLeft"
  command   = "[term] --class=taskbar -e btm -b"
  class     = "taskbar"
  size      = "30% 80%"
  offset    = "200%"
