[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "a63550b"
hash = "c2021386289a0cbb3e152a052f67c177"

[[plugin.deps]]
use = "Reledia/glow"
rev = "bd3eaa5"
hash = "92b5c58159a51c567f82b618cee2b78"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "7fb073f"
hash = "a3e32d62ea3cc703e6bf677bdb18a544"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "cc12f3f"
hash = "b92e44ad5004f1b45e5c3d717a60ed24"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "bb941c4"
hash = "956b02fe8213e7b92e21a941b9abe764"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "843c3fa"
hash = "b4040931f0d2f9670ddb4923e55cd881"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "b886025"
hash = "1adc12c2b2b025411ab61eb8f0879574"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = "b886025"
hash = "a9d553bd19a3cd7f4eab3abaac5d67ff"

[flavor]
deps = []
