[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "6c639b4"
hash = "5614c46d5de76623c283d415bfac8025"

[[plugin.deps]]
use = "Reledia/glow"
rev = "c76bf4f"
hash = "a6b78bf9af5390e3a85a6951fbb7b93"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "f8879b3"
hash = "d378328e5d0a1b9fb9f04ab3aade4575"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "447fe95"
hash = "dcaebc8bc261206f6b59e2c67464af5"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "ce6fb75"
hash = "ed6c185514109d7c5463f609282b220c"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "2559e5f"
hash = "c9a3d0731e7d7340e2c6d6126b1f3aa3"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "92f78dc"
hash = "2f1053f89d1a301a648ab181d0948e38"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = "92f78dc"
hash = "f0c4b41b5d19a3144958383333eff6e7"

[flavor]
deps = []
