[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "a63550b"
hash = "c2021386289a0cbb3e152a052f67c177"

[[plugin.deps]]
use = "Reledia/glow"
rev = "bd3eaa5"
hash = "92b5c58159a51c567f82b618cee2b78"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "7fb073f"
hash = "a3e32d62ea3cc703e6bf677bdb18a544"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "0e2ae47"
hash = "6656f2869ae2274a0e1860876f15186f"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "0742fff"
hash = "2bd799b42b8e42b8ef100310be71f8d1"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "843c3fa"
hash = "b4040931f0d2f9670ddb4923e55cd881"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "e95c7b3"
hash = "1adc12c2b2b025411ab61eb8f0879574"

[[plugin.deps]]
use = "yazi-rs/plugins:full-border"
rev = "e95c7b3"
hash = "3996fc74044bc44144b323686f887e1"

[[plugin.deps]]
use = "yazi-rs/plugins:mount"
rev = "e95c7b3"
hash = "e1de3054c0d1a2d8dc6f007eadc0fa31"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "e95c7b3"
hash = "63b6c222bf2103b3023389dde5e2ecfe"

[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = "e95c7b3"
hash = "d6f60c24d8c0cf57a855bf46115b2502"

[[plugin.deps]]
use = "yazi-rs/plugins:zoom"
rev = "e95c7b3"
hash = "4a47a9cd4d8b3a963cb4cc593664b77e"

[[plugin.deps]]
use = "ahkohd/eza-preview"
rev = "43913fa"
hash = "931a7f3452f74c1f1f499357002a1cae"

[flavor]
deps = []
