[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "a63550b"
hash = "733c7340b1ca2d3ef274c427a0cf21b"

[[plugin.deps]]
use = "Reledia/glow"
rev = "bd3eaa5"
hash = "f8d302ba41ab9deb4133fe3d0a64b6c6"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "7fb073f"
hash = "c52246362f02c69cc8cf9c9929b567a1"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "0e2ae47"
hash = "fb2277a27f8d819d73db516f11b11582"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "0742fff"
hash = "8803b7801055d3d3a59c6f90ffb79a22"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "843c3fa"
hash = "56397401675a83833f14283d8de96abf"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "e95c7b3"
hash = "780a6bc3271c895c85119937cf47149"

[[plugin.deps]]
use = "yazi-rs/plugins:full-border"
rev = "e95c7b3"
hash = "b16b6e08085a3dfec72335415e4c83ed"

[[plugin.deps]]
use = "yazi-rs/plugins:mount"
rev = "e95c7b3"
hash = "6aa17d50c0dd49a51b77cf57e4d2409"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "e95c7b3"
hash = "e65e6528de15012b5ccdead4ed26b8bd"

[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = "e95c7b3"
hash = "e671ad6617800ea6adae1ede7930c105"

[[plugin.deps]]
use = "yazi-rs/plugins:zoom"
rev = "e95c7b3"
hash = "6a802572270653c14379ab6acf800787"

[[plugin.deps]]
use = "ahkohd/eza-preview"
rev = "a97cf55"
hash = "8e2173449f8542f3a37d4b4df12c954e"

[flavor]
deps = []
