[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "a63550b"
hash = "c2021386289a0cbb3e152a052f67c177"

[[plugin.deps]]
use = "Reledia/glow"
rev = "bd3eaa5"
hash = "92b5c58159a51c567f82b618cee2b78"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "7fb073f"
hash = "a3e32d62ea3cc703e6bf677bdb18a544"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "b74b7b8"
hash = "4b6ac1a6fd7ba02a945070ad39fc1999"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "1ee69a5"
hash = "63679f3daf8551ff8755be38b5ced0f"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "843c3fa"
hash = "b4040931f0d2f9670ddb4923e55cd881"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "2ad42fa"
hash = "1adc12c2b2b025411ab61eb8f0879574"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = "2ad42fa"
hash = "a9d553bd19a3cd7f4eab3abaac5d67ff"

[flavor]
deps = []
