[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "a63550b"
hash = "733c7340b1ca2d3ef274c427a0cf21b"

[[plugin.deps]]
use = "Reledia/glow"
rev = "bd3eaa5"
hash = "f8d302ba41ab9deb4133fe3d0a64b6c6"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "7fb073f"
hash = "c52246362f02c69cc8cf9c9929b567a1"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "cc12f3f"
hash = "4c0b8f7e27455f5ac19ee7e01434d771"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "0742fff"
hash = "8803b7801055d3d3a59c6f90ffb79a22"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "843c3fa"
hash = "56397401675a83833f14283d8de96abf"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "b886025"
hash = "780a6bc3271c895c85119937cf47149"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = "b886025"
hash = "216a7e0260d83fe146f21ed8bae201fd"

[flavor]
deps = []
