[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "a63550b"
hash = "733c7340b1ca2d3ef274c427a0cf21b"

[[plugin.deps]]
use = "Reledia/glow"
rev = "bd3eaa5"
hash = "f8d302ba41ab9deb4133fe3d0a64b6c6"

[[plugin.deps]]
use = "AnirudhG07/nbpreview"
rev = "7fb073f"
hash = "c52246362f02c69cc8cf9c9929b567a1"

[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "f89605c"
hash = "8450ddc10853919844b9d65ab8efe511"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "0742fff"
hash = "8803b7801055d3d3a59c6f90ffb79a22"

[[plugin.deps]]
use = "AnirudhG07/rich-preview"
rev = "843c3fa"
hash = "56397401675a83833f14283d8de96abf"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "de53d90"
hash = "780a6bc3271c895c85119937cf47149"

[[plugin.deps]]
use = "yazi-rs/plugins:full-border"
rev = "de53d90"
hash = "b16b6e08085a3dfec72335415e4c83ed"

[[plugin.deps]]
use = "yazi-rs/plugins:mount"
rev = "de53d90"
hash = "88b42fd123aeaa31b336e3b2f3d53289"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "de53d90"
hash = "e65e6528de15012b5ccdead4ed26b8bd"

[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = "de53d90"
hash = "e671ad6617800ea6adae1ede7930c105"

[[plugin.deps]]
use = "yazi-rs/plugins:zoom"
rev = "de53d90"
hash = "6a802572270653c14379ab6acf800787"

[[plugin.deps]]
use = "ahkohd/eza-preview"
rev = "b114b01"
hash = "de4d8aa68ed73157c6359fc3d1510c14"

[flavor]
deps = []
