[[mgr.prepend_keymap]]
  on   = ["<"]
  run  = "tab_switch -1 --relative"
  desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
  on   = [">"]
  run  = "tab_switch 1 --relative"
  desc = "Switch to next tab"

[[mgr.prepend_keymap]]
  on   = ["g", "t"]
  run  = "cd ~/.local/share/Trash"
  desc = "Go Trash"

[[mgr.prepend_keymap]]
  on   = ["g", "z"]
  run  = "cd ~/.local/share/chezmoi"
  desc = "Go cheZmoi"

[[mgr.prepend_keymap]]
  on   = ["g", "r"]
  run  = "cd /"
  desc = "Go Root"

[[mgr.prepend_keymap]]
  on   = ["g", "w"]
  run  = "cd /mnt/Windows"
  desc = "Go Windows"

[[mgr.prepend_keymap]]
  on   = ["g", "n"]
  run  = "cd /mnt/NAS"
  desc = "Go NAS"

  # [[mgr.prepend_keymap]]
  #   on   = "+"
  #   run  = "plugin zoom 1"
  #   desc = "Zoom in hovered file"

  # [[mgr.prepend_keymap]]
  #   on   = "-"
  #   run  = "plugin zoom -1"
  #   desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
  on   = "T"
  run  = "plugin toggle-pane max-preview"
  desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
  on   = ["E"]
  run  = "plugin eza-preview"
  desc = "Toggle tree/list dir preview"

[[mgr.prepend_keymap]]
  on   = ["C"]
  run  = "plugin ouch --args=zip"
  desc = "Compress with ouch"

[[mgr.prepend_keymap]]
  on   = ["c", "m"]
  run  = "plugin chmod"
  desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
  on   = "!"
  run  = 'shell "env DISABLE_BACK2DIR=1 $SHELL" --block'
  desc = "Open shell here"

[[mgr.prepend_keymap]]
  on   = "M"
  run  = "plugin mount"
  desc = "Mount plugin"

[[mgr.prepend_keymap]]
  on   = "<a-z>"
  run  = 'shell -- zoxide add "$@"'
  desc = "Add selection to zoxide"
