[config]

  [config.custom_keywords]
    font = "JetBrainsMono Nerd Font"

  [config.custom_colors]
    red     = { color = "#FF0000", blend = true }
    blue    = { color = "#0000FF", blend = true }
    green   = { color = "#00FF00", blend = true }
    yellow  = { color = "#FFFF00", blend = true }
    fuchsia = { color = "#FF00FF", blend = true }
    cyan    = { color = "#00FFFF", blend = true }
    orange  = { color = "#FF0000", blend = true }

[templates.hyprland]
  input_path  = "templates/hyprland-colors.conf"
  output_path = "~/.config/hypr/colors/matugen.conf"
  post_hook   = "hyprctl reload"

[templates.waybar]
  input_path  = "templates/colors.css"
  output_path = "~/.config/waybar/colors/matugen.css"

[templates.kitty]
  input_path  = "templates/kitty-colors.conf"
  output_path = "~/.config/kitty/colors/matugen.conf"

  # [templates.gtk3]
  #   input_path  = "templates/gtk-colors.css"
  #   output_path = "~/.config/gtk-3.0/gtk.css"
  #   post_hook   = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
  input_path  = "templates/gtk-colors.css"
  output_path = "~/.config/gtk-4.0/gtk.css"
